### ISSUE TITLE
Thanks for all the effort and a little token of my appreciation

### ISSUE THREAD

**Issue by HamsterHuey** [colinleach/probinf-notes#1]
Hey Colin, Thanks so much for taking the effort to put these notes together! It's been awesome and I'm really glad to have them on hand as a quick reference. In case you didn't get around to doing it, I did the rather tedious job of converting all the HW, Exercise and Projects with solutions to PDF and figured I'd share it with you:
https://dl.dropboxusercontent.com/u/23650512/Course%20Notes.zip

Let me know whenever you grab it so I can remove it since I plan on holding onto this privately just for my own reference and don't want to violate the honor code.

Cheers

PS - Sorry for abusing the "Issues" feature of your repo but I didn't know any other way to get in touch.

**Comment by colinleach** [comment]
Thanks for that! I've downloaded your files, so delete them when you wish.
All the best,
Colin

**Comment by HamsterHuey** [comment]
Awesome! Took it offline. Thanks again.
Cheers,
Sudeep
